### Variables
@baseUrl = http://localhost:5000

@userName = saif.rashiduddin@gmail.com
@password = Lk9375msr!
@newPassword = Lk9375msr@
@firstName = Mustapha
@lastName = Rashiduddin

@userName2 = bob.harry@gmail.com
@password2 = Lk9375msr@
@firstName2 = bob
@lastName2 = harry

### Register a user ######################################################
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "userName": "{{userName}}",
  "password": "{{password}}",
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}"
}

# @lang=lua
> {%
local json = vim.json.decode(response.body)
vim.fn.setenv("TOKEN", json.token)
%}

### Register user2 ######################################################
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "userName": "{{userName2}}",
  "password": "{{password2}}",
  "firstName": "{{firstName2}}",
  "lastName": "{{lastName2}}"
}

# @lang=lua
> {%
local json = vim.json.decode(response.body)
vim.fn.setenv("TOKEN", json.token)
%}

### Login user 1 #########################################################
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "userName": "{{userName}}",
  "password": "{{password}}"
}

# @lang=lua
> {%
local json = vim.json.decode(response.body)
vim.fn.setenv("TOKEN", json.token)
%}

### Login user2 #########################################################
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "userName": "{{username2}}",
  "password": "{{password2}}"
}

# @lang=lua
> {%
local json = vim.json.decode(response.body)
vim.fn.setenv("TOKEN", json.token)
%}

### Logout user1 ########################################################
POST {{baseUrl}}/auth/logout
Content-Type: application/json

### Request password reset ###############################################
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
  "userName": "{{userName}}"
}

# @lang=lua
> {%
local json = vim.json.decode(response.body)
vim.fn.setenv("RESET_TOKEN", json.resetToken)
%}

### Verify reset token ###################################################
POST {{baseUrl}}/auth/verify-reset-token
Content-Type: application/json

{
  "resetToken": "{{RESET_TOKEN}}"
}

### Reset password with verified token ###################################
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json

{
  "userName": "{{userName}}",
  "resetToken": "{{RESET_TOKEN}}",
  "newPassword": "{{newPassword}}"
}

### Reset password when logged in ########################################
POST {{baseUrl}}/auth/change-password-logged-in
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "currentPassword": "{{password}}",
  "newPassword": "{{newPassword}}"
}

###########################################################################
# postRoutes
###########################################################################
POST {{baseUrl}}/posts/create
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "mPost": "this is my blog welcome blabla i have a glass of water blabla it has salt in it"
}

############################################################################
POST {{baseUrl}}/posts/create
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "mPost": "i am posting a post which is a post in which i post"
}

### Read all posts #########################################################
GET {{baseUrl}}/posts/read-all
Authorization: {{TOKEN}}
Content-Type: application/json

### Request 1 post using id ################################################
GET {{baseUrl}}/posts/read/2
Authorization: {{TOKEN}}
Content-Type: application/json

### change post 1 ##########################################################
PUT {{baseUrl}}/posts/edit/1
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "mPost": "haha"
}

### delete post 1 ##########################################################
DELETE {{baseUrl}}/posts/delete/2
Authorization: {{TOKEN}}
Content-Type: application/json

############################################################################
### CommentRoutes
############################################################################

###  create comment ########################################################
POST {{baseUrl}}/comments/create
Authorization: {{TOKEN}}
Content-Type: application/json

{
  "mComment": "lala",
  "postId": 2
}

### create another comment #################################################
POST {{baseUrl}}/comments/create
Authorization: {{TOKEN}}

{
  "mComment": "babababa",
  "postId": 2
}

### create another comment #################################################
POST {{baseUrl}}/comments/create
Authorization: {{TOKEN}}

{
  "mComment": "trolololo",
  "postId": 1
}


### edit a comment ########################################################
PUT {{baseUrl}}/comments/edit/2
Authorization: {{TOKEN}}

{
  "mComment": "updated comment lol"
}

### delete a comment #######################################################
DELETE {{baseUrl}}/comments/delete/3
Authorization: {{TOKEN}}

### get all post comments #######################################################
GET {{baseUrl}}/comments/read-post-comments/2
Authorization: {{TOKEN}}

### get all post comments #######################################################
GET {{baseUrl}}/comments/read-post-comments/1
Authorization: {{TOKEN}}
